# Generated by Django 4.0 on 2021-01-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_text', models.CharField(max_length=50)),
                ('out_text', models.CharField(max_length=50)),
            ],
        ),
    ]
