# Generated by Django 4.0 on 2021-01-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeweather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
